server {
    listen 127.0.0.1:8081;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Content-Type-Options nosniff always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}